/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('daisyui')
  ],
  daisyui: {
    themes: [
      {
        toulouse: {
          "primary": "#E4003A",
          "primary-content": "#FFFFFF",
          "secondary": "#6B2E8C",
          "secondary-content": "#FFFFFF",
          "accent": "#D4AF37",
          "accent-content": "#2A2623",
          "neutral": "#D1CBC4",
          "neutral-content": "#2A2623",
          "base-100": "#F5F3F0",
          "base-200": "#E8E4DF",
          "base-300": "#D1CBC4",
          "base-content": "#2A2623",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        nocturne: {
          "primary": "#1E40AF",
          "primary-content": "#FFFFFF",
          "secondary": "#94A3B8",
          "secondary-content": "#0F172A",
          "accent": "#06B6D4",
          "accent-content": "#0F172A",
          "neutral": "#334155",
          "neutral-content": "#F1F5F9",
          "base-100": "#0F172A",
          "base-200": "#1E293B",
          "base-300": "#334155",
          "base-content": "#F1F5F9",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        clown: {
          "primary": "#EF4444",
          "primary-content": "#FFFFFF",
          "secondary": "#FBBF24",
          "secondary-content": "#78350F",
          "accent": "#84CC16",
          "accent-content": "#FFFFFF",
          "neutral": "#FDE68A",
          "neutral-content": "#78350F",
          "base-100": "#FFFBEB",
          "base-200": "#FEF3C7",
          "base-300": "#FDE68A",
          "base-content": "#78350F",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#22C55E",
          "success-content": "#FFFFFF",
          "warning": "#FB923C",
          "warning-content": "#FFFFFF",
          "error": "#DC2626",
          "error-content": "#FFFFFF",
        },
        azure: {
          "primary": "#0078D4",
          "primary-content": "#FFFFFF",
          "secondary": "#69AFE5",
          "secondary-content": "#323130",
          "accent": "#F7630C",
          "accent-content": "#FFFFFF",
          "neutral": "#EDEBE9",
          "neutral-content": "#323130",
          "base-100": "#FFFFFF",
          "base-200": "#F3F2F1",
          "base-300": "#EDEBE9",
          "base-content": "#323130",
          "info": "#0078D4",
          "info-content": "#FFFFFF",
          "success": "#107C10",
          "success-content": "#FFFFFF",
          "warning": "#F7630C",
          "warning-content": "#FFFFFF",
          "error": "#D13438",
          "error-content": "#FFFFFF",
        },
        forest: {
          "primary": "#047857",
          "primary-content": "#FFFFFF",
          "secondary": "#34D399",
          "secondary-content": "#14532D",
          "accent": "#92400E",
          "accent-content": "#FFFFFF",
          "neutral": "#BBF7D0",
          "neutral-content": "#14532D",
          "base-100": "#F0FDF4",
          "base-200": "#DCFCE7",
          "base-300": "#BBF7D0",
          "base-content": "#14532D",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#FBBF24",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        sunset: {
          "primary": "#F97316",
          "primary-content": "#FFFFFF",
          "secondary": "#EC4899",
          "secondary-content": "#FFFFFF",
          "accent": "#A855F7",
          "accent-content": "#FFFFFF",
          "neutral": "#FED7AA",
          "neutral-content": "#7C2D12",
          "base-100": "#FFF7ED",
          "base-200": "#FFEDD5",
          "base-300": "#FED7AA",
          "base-content": "#7C2D12",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#FBBF24",
          "warning-content": "#FFFFFF",
          "error": "#DC2626",
          "error-content": "#FFFFFF",
        },
        ocean: {
          "primary": "#0891B2",
          "primary-content": "#FFFFFF",
          "secondary": "#38BDF8",
          "secondary-content": "#164E63",
          "accent": "#F472B6",
          "accent-content": "#FFFFFF",
          "neutral": "#A5F3FC",
          "neutral-content": "#164E63",
          "base-100": "#ECFEFF",
          "base-200": "#CFFAFE",
          "base-300": "#A5F3FC",
          "base-content": "#164E63",
          "info": "#06B6D4",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#FBBF24",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        medical: {
          "primary": "#2563EB",
          "primary-content": "#FFFFFF",
          "secondary": "#94A3B8",
          "secondary-content": "#1E293B",
          "accent": "#10B981",
          "accent-content": "#FFFFFF",
          "neutral": "#F1F5F9",
          "neutral-content": "#1E293B",
          "base-100": "#FFFFFF",
          "base-200": "#F8FAFC",
          "base-300": "#F1F5F9",
          "base-content": "#1E293B",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        lavande: {
          "primary": "#8B5CF6",
          "primary-content": "#FFFFFF",
          "secondary": "#F0ABFC",
          "secondary-content": "#581C87",
          "accent": "#FCD34D",
          "accent-content": "#581C87",
          "neutral": "#E9D5FF",
          "neutral-content": "#581C87",
          "base-100": "#FAF5FF",
          "base-200": "#F3E8FF",
          "base-300": "#E9D5FF",
          "base-content": "#581C87",
          "info": "#3B82F6",
          "info-content": "#FFFFFF",
          "success": "#10B981",
          "success-content": "#FFFFFF",
          "warning": "#FBBF24",
          "warning-content": "#FFFFFF",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
        cupcake: {
          "primary": "#F472B6",
          "primary-content": "#FFFFFF",
          "secondary": "#93C5FD",
          "secondary-content": "#831843",
          "accent": "#6EE7B7",
          "accent-content": "#831843",
          "neutral": "#FBCFE8",
          "neutral-content": "#831843",
          "base-100": "#FDF2F8",
          "base-200": "#FCE7F3",
          "base-300": "#FBCFE8",
          "base-content": "#831843",
          "info": "#60A5FA",
          "info-content": "#FFFFFF",
          "success": "#34D399",
          "success-content": "#FFFFFF",
          "warning": "#FBBF24",
          "warning-content": "#FFFFFF",
          "error": "#F87171",
          "error-content": "#FFFFFF",
        },
      }
    ],
    darkTheme: "nocturne",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}
